### ISSUE TITLE
A problem occurred with configuring project ':gdal'.

### ISSUE THREAD

**Issue by jfacoustic** [paamand/GDAL#3]
Simply trying to build project in Android Studio gives the message:

```
org.gradle.api.ProjectConfigurationException: A probelm occured configuring project ':gdal'.
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.GradleException: executing external native build for cmake ./gdal/CMakeLists.txt
```

Similarly to issue #1, I am getting syncing errors as well.  

I tried changing 
`add_library( gdalwrap SHARED src/main/cpp/gdal_wrap.cpp )`
to
`add_library( gdalwrap SHARED ../submodules/gdal/gdal/swig/python/extensions/gdal_wrap.cpp
`
but it made no difference.

**Comment by jfacoustic** [comment]
@paamand I noticed there's a file under the submodules called install.sh.
Is this something that I need to run?

**Comment by paamand** [comment]
Updated the readme to make that clear. You need to build the 'install' build type first which handles all the not-so-nice stuff of cross-compiling the library dependencies and packaging the wrapper headers. Then the rest should be straight forward.

**Comment by jfacoustic** [comment]
Awesome!  Thanks so much.  I'll give it a go

**Comment by jfacoustic** [comment]
<img width="623" alt="screen shot 2019-02-04 at 2 33 03 pm" src="https://user-images.githubusercontent.com/10293788/52238683-de7ee700-2889-11e9-9a62-f46b3b0d993e.png">

@paamand I'm not able to even select a build variant.

**Comment by jfacoustic** [comment]
Is there a way to do this in the terminal?  I tried running `./gradlew assembleInstall` but it's taking forever.

**Comment by paamand** [comment]
The cross-compiling takes quite a while. Around 20mins on my Dell XPS15.
I just did a fresh checkout and opened the project. No problem detecting the gradle config:
![screenshot from 2019-02-04 22-57-52](https://user-images.githubusercontent.com/17837300/52240237-a77ff400-28d0-11e9-85aa-b3967604762d.png)

What Android Studio version and OS are you running?

**Comment by jfacoustic** [comment]
I'm using Android Studio 3.3 on MacOS Mojave.   I might give it a go on my Linux Thinkpad later tonight.

Here's the results so far with that `./gradlew assembleInstall`:

<img width="732" alt="screen shot 2019-02-04 at 3 06 04 pm" src="https://user-images.githubusercontent.com/10293788/52240573-71ba1b80-288e-11e9-8ba4-6f455954919e.png">

**Comment by paamand** [comment]
Otherwise try running install.sh from the APP_ROOT folder (GDAL/gdal). Notice the two arguments:
`commandLine 'sh', '../submodules/install.sh', "$ndkDir", "$minSdkVer"`

The cross-compilation is pretty separate from the actual project.

**Comment by jfacoustic** [comment]
That doesn't work.  It hits `configure: error: C compiler cannot create executables`
Maybe it's because I'm using Clang instead of GCC?

**Comment by jfacoustic** [comment]
I also notice the error:
`libtool:    error: 'lib*jni.a' is not a valid libtool archive'`

**Comment by paamand** [comment]
No, in the install.sh the compiler is specified to clang (which also is the only supported option for native cross compilation): `CC="arm-linux-androideabi-clang"`

Also, it is the NDK-toolchain compiler, which is produced through `$NDK_ROOT/build/tools/make-standalone-toolchain.sh` in the install.sh.

If you comment out line 18-24 (externalNativeBuild) of `GDAL/gdal/build.gradle` you should be able to configure the project with build type 'install' doing the work.

Also, did you check out the submodules,or are they empty folders?! (`git clone --recurse-submodules https://github.com/paamand/GDAL.git`)

**Comment by jfacoustic** [comment]
Yes,  I had cloned the repository recursively.  

What OS/Android Studio version are you using?

**Comment by paamand** [comment]
Ubuntu 18.04.1 LTS
Was Android Studio 3.1. Now upgraded to 3.3.
I am currently trying to build through `./gradlew installFromSource`.
UPDATE: Build was successful.

There may be a bit of OS-specific configuration in install.sh. Also, GDAL itself is not perfect in compatibility. Would be great if you tried on a Linux distro.

**Comment by jfacoustic** [comment]
Ok, I'll try it on Linux later tonight when I get home, then I'll let you know if anything changes.  Thanks so much for your help

**Comment by jfacoustic** [comment]
@paamand I'm still getting the issue with Android Studio 3.3 in Ubuntu.  
I've got NDK installed as well.  I'll try the `./gradlew installFromSource`

**Comment by paamand** [comment]
@jfacoustic I'm able to reproduce your problem of not seeing the build types in Android Studio 3.3. No idea why it works in 3.1.3. the `installFromSource` commandline still worked and the libs are build, but the project does not. I will look into it.
//R

**Comment by jfacoustic** [comment]
Hmm.  That's weird that something would break between minor releases.  
Thanks for your help.

I finally managed to get it to compile with `./gradlew installFromSource`.  It took an hour and a half on my Thinkpad...

**Comment by paamand** [comment]
Good to hear. Did the project also compile to produce the .aar files? And if so, could you suggest a bug-fix or amendment to the Readme?
It seems that they have changed how build variants are handled for native builds in Android Studio 3.3.

**Comment by jfacoustic** [comment]
Not sure.  Where would the .aar files be found?  Sorry, I'm new to Android development.  

It seems like Android Studio 3.3 introduced "Single variant builds."  I'm not sure if this would affect the compilation, but here's more information:

https://developer.android.com/studio/releases/#single-variant

**Comment by jfacoustic** [comment]
@CalebGartner is going to try to work on this too.

**Comment by paamand** [comment]
@jfacoustic @CalebGartner
Seems that I had forgot to mkdir the required dirs for wrappers and libs in the project. Fixed now.
Thansk for the heads up on single variant builds. I realize that the `install` variant probably is not an actual variant. But I'm not too keen with gradle, and if anyone can rewrite the `build.gradle` to check for the submodule installation that would be great. Current procedure is to run the install.sh through `gradlew installFromSource` before the debug/release builds can be gradle-synced and build.

I think the problem is fixed now, as it builds and produces the .aar files (found in `GDAL/gdal/build/outputs/aar`).

**Comment by jfacoustic** [comment]
I'll try it out sometime this weekend.  Thanks for figuring this out.

**Comment by CalebGartner** [comment]
I'll try it out as well and see if I can edit the gradle build file. Thanks @paamand.

**Comment by jfacoustic** [comment]
I still can't get the syncing to work

**Comment by jfacoustic** [comment]
I've ran gradlew installFromSource, but still no luck (Also,  on latest commit).  It's that "SIMPLE: error configuring" issue.  It has to do with CMake, but the logs don't say anything useful.  This is all they say:

```
2019-02-11 10:49:32,665 [d thread 9]   INFO - e.project.sync.GradleSyncState - Started setup of project 'GDAL'. 
2019-02-11 10:49:32,669 [entQueue-0]   INFO - idea.project.IndexingSuspender - Consuming IndexingSuspender activation event: SETUP_STARTED 
2019-02-11 10:49:32,702 [d thread 9]   INFO - ule.android.SdkModuleSetupStep - Set Android SDK 'Android API 26 Platform' (/Users/jfmathews/Library/Android/sdk) to module 'gdal' 
2019-02-11 10:49:32,975 [entQueue-0]   INFO - e.project.sync.GradleSyncState - Gradle sync failed (1 s 514 ms) 
2019-02-11 10:49:32,988 [entQueue-0]   INFO - idea.project.IndexingSuspender - Consuming IndexingSuspender deactivation event: SYNC_FINISHED 
```

**Comment by jfacoustic** [comment]
I finished `gradlew installFromSource` on my Mac.  No GDAL/gdal/build/outputs/aar.  Didn't even create the build directory

**Comment by paamand** [comment]
The purpose of the `installFromSource` is to prebuild the gdal libraries.
Then building the project itself links and packages the wrapper in the .aar
file.

Did it create the /libs folder and can you find the *.so libraries in it?

//R

man. 11. feb. 2019 18.54 skrev Josh <notifications@github.com>:

**Comment by CalebGartner** [comment]
Hi @paamand. I managed to successfully build it on my system. It ended up being some external dependencies and some environment variables that Android Studio needed.

Previously, the install.sh script was silently failing if it didn't have the dependencies it needed, which explains why not all the files were generated correctly.

I'll submit a PR later tonight. Thanks for your help/patience!

**Comment by jfacoustic** [comment]
Think we are ready to close this issue?

**Comment by GrayCygnus** [comment]
I am having a similar issue to some of the things you commented above (like the lib*jni thing). More specifically, when running `installFromSource` the libjni.so and libproj.so files are missing... will try to solve it and, in case I can't overcome it, post a separate Issue :)

**Comment by paamand** [comment]
Closing this issue. The install script was updated and the README now includes instructions on how to call the install script with paths.
